version: '3.7'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: all_a
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    #command: --init-file /data/application/init.sql
    #volumes:
    #    - ./init.sql:/data/application/init.sql

volumes:
  mysql_data:
